@startuml
skinparam defaultTextAlignment left
caption Behavior of thing TimerJava
[*] --> SoftTimer
state SoftTimer{
state default{
	default : m:timer?timer_start / [m.delay > 0]\naction ...\n
	default : m:timer?timer_cancel / \naction ...\n
}
[*] --> default
}
@enduml
