@startuml Temperature controll
mainframe Temperature controll

'PIM
rectangle pim:PIM {
    portout get_sensor

    portout request_sensor
    portout request_actuator

    portout human_output
    portout human_input

    'guards
    port guard_temperature
    port guard_human
}

'PSM
rectangle psm:PSM {
    portin require_val

    portin provide_temp
    portin provide_lum_motion

    portout MQTT
}

'Energy saver
rectangle es:Energy_saver {
    portin get_cmd
    
    portout provide_cmd
}

rectangle test:Test {
    'from sim
    portin toMQTT

    'from human
    portout send_cmd
    portout get_values
}

'HUMAN
send_cmd --> human_input
send_cmd --> get_cmd

'pim
human_output --> get_values
request_actuator --> require_val
request_sensor --> require_val

'psm
provide_temp --> get_sensor
provide_lum_motion --> get_cmd
MQTT <--> toMQTT

'Energy saver
provide_cmd -> human_input

@enduml