@startuml Temprature controll
mainframe Temprature controll

'PIM
rectangle pim:PIM {
    'left
    portout get_sensor
    portout request_sensor
    portout request_actuator
    
    'right
    portout human_output
    portout human_input

    'guard
    portin guard_temperature
    portin guard_human
}

'PSM
rectangle psm:PSM {
    'left
    portin provide_temp
    portin require_val

    'right
    portout MQTT
}

'Energy saver
rectangle es:Energy_saver {
    portin es_send_cmd
    
    portout es_get_cmd
}

'Test thing
rectangle test:Test {
    portin t_get_values
    portin t_send_cmd

    portout t_MQTT
}

rectangle g_temp:TimerJava {
    portout temp_timer
}

rectangle g_humn:TimerJava {
    portout humn_timer
}

'Human
t_send_cmd --> human_input

t_send_cmd ---> es_get_cmd

'PIM
human_output ---> t_get_values
request_sensor ---> require_val
request_actuator ---> require_val

'PSM
provide_temp --> get_sensor

'MQTT
t_MQTT <--> MQTT

'Energy saver
es_send_cmd ---> human_input

'Guard temp
temp_timer --> guard_temperature

'Guard human
humn_timer --> guard_human

@enduml