@startuml sequense diagram

mainframe set name here
participant "simulation:sim" as sim
participant "psm:PSM" as psm
participant "pim:PIM" as pim
participant "enerty_saver:ES" as es
actor "myself:Human" as human

es <- human : set_temperature(preferred_temp)
pim <- es : set_temperature(preferred_temp)
psm <- es: add_light_sensor(id1, txt1)
psm <- pim: add_thermometer(id1, txt1)
psm <- pim: add_device(didid1, didtxt1)
pim -> human : prompt("Now entering thermostat")

loop luminance change
    sim -> es: luminence(id1, lightval)

    alt 
        |||
        else lightval < light_on_value
            pim <- es: set_temperature(preferred_temp)
        else lightval >= light_on_value
            pim <- es: set_temperature(preferred_temp - temp_dark_offsett)
    end
end

loop regulate temprature
    sim -> pim: temperature(id1, txt1, temp2)
    alt 
        |||
        else temp2 < temp1 - temp_diff
            pim -> sim: SwitchOn(did1)
        else temp2 >= temp1 + temp_diff
            pim -> sim: SwitchOff(did1)
    end

end

sim <- human: SwitchOn(did1)
sim <- human: SwitchOff(did1)

@enduml
