@startuml sequense diagram
mainframe set name here


participant "psm:PSM" as psm
participant "pim:PIM" as pim
participant "enerty_saver:ES" as es
participant "simulation:sim" as sim


'Set preferred temp
es <- sim: set_temperature(prefered_temp{23})
es -> pim: set_luminance({50})
pim <- es: set_temperature(prefered_temp{23})

psm <- es: add_lightsensor(1, "")

psm <- pim: add_thermometer(1, "")
psm <- pim: add_device(didid1, didtxt1)

pim -> sim: prompt("Now entering thermostat")

hnote across: day and light on
'setup compleat

sim -> psm: temprature(1, "", 15)
psm -> pim: temprature(1, "", 15)
pim -> es: temprature(1, "", 15)

sim -> es: luminence(1, "", 20_000)
sim <- pim: switch_on(1)

hnote across: some time later

sim -> psm: temprature(1, "", 25)
psm -> pim: temprature(1, "", 25)
pim -> es: temprature(1, "", 25)

sim -> es: luminence(1, "", 20_000)
sim <- pim: switch_off(1)

hnote across: lights off

sim -> psm: temprature(1, "", 23)
psm -> pim: temprature(1, "", 23)
pim -> es: temprature(1, "", 23)

sim -> es: luminence(1, "", 40)

pim <- es: set_temperature(prefered_temp{23} - temp_diff{2})

sim <- pim: switch_off(1)

hnote across: some time later

sim -> psm: temprature(1, "", 20)
psm -> pim: temprature(1, "", 20)
pim -> es: temprature(1, "", 20)

sim -> es: luminence(1, "", 40)
sim <- pim: switch_on(1)

hnote across: night start

sim -> es: Timer for night activate
sim -> psm: temprature(1, "", 20)
psm -> pim: temprature(1, "", 20)
pim -> es: temprature(1, "", 20)

sim -> es: luminence(1, "", 40)

pim <- es: set_temperature(prefered_temp{20} - temp_night_diff{8})
sim <- pim: switch_off(1)

hnote across: some time later

sim -> psm: temprature(1, "", 14)
psm -> pim: temprature(1, "", 14)
pim -> es: temprature(1, "", 14)

sim -> es: luminence(1, "", 40)

sim <- pim: switch_on(1)

hnote across: day start, but light off

sim -> es: Timer for day activate

sim -> psm: temprature(1, "", 15)
psm -> pim: temprature(1, "", 15)
pim -> es: temprature(1, "", 15)

sim -> es: luminence(1, "", 40)

pim <- es: set_temperature(prefered_temp{15} - temp_diff{2})
sim <- pim: switch_on(1)

hnote across: day continue, light turns on

sim -> es: Timer for day activate

sim -> psm: temprature(1, "", 15)
psm -> pim: temprature(1, "", 15)
pim -> es: temprature(1, "", 15)

sim -> es: luminence(1, "", 200)

pim <- es: set_temperature(prefered_temp{15})
sim <- pim: switch_on(1)


@enduml
