@startuml
skinparam defaultTextAlignment left
caption Behavior of thing MQTTDriver
[*] --> behaviorMQTTDriver
state behaviorMQTTDriver{
state Alive1{
	Alive1 : entry / ...\n

Alive1 --> Alive2 : alv:require_val?iamalive1\naction ...\n

Alive1 --> Idle : alv:require_val?iamalive2\naction ...\n
}
state Alive2{

Alive2 --> Idle : alv:require_val?iamalive2
}
state Idle{





Idle --> Idle : swoff:require_val?SwitchOff\naction ...\n\n||swon:require_val?SwitchOn\naction ...\n\n||add_dev:require_val?add_device\naction ...\n\n||addt:require_val?add_thermometer\naction ...\n\n||put_t:MQTT?temperature\naction ...\n
}
[*] --> Alive1
}
@enduml
